// auth.js	
export const AJAX_ERROR 			= 'AJAX_ERROR'
//USERS 
export const USERS_LIST 			= 'USERS_LIST'
export const GET_ROLES_DATA 		= 'GET_ROLES_DATA'
export const CREATE_USER 			= 'CREATE_USER'
export const DELETE_USER 			= 'DELETE_USER'
export const GET_USER_DATA 			= 'GET_USER_DATA'

//SALES 
export const SALES_LIST 			= 'SALES_LIST'
export const CREATE_SALES 			= 'CREATE_SALES'
export const DELETE_SALES			= 'DELETE_SALES'
export const GET_SALES_DATA 	    = 'GET_SALES_DATA'
export const EDIT_SALES 	    	= 'EDIT_SALES'

//DOCTOR 
export const DOCTOR_LIST 			= 'DOCTOR_LIST'
export const CREATE_DOCTOR 			= 'CREATE_DOCTOR'
export const DELETE_DOCTOR			= 'DELETE_DOCTOR'
export const GET_DOCTOR_DATA 	    = 'GET_DOCTOR_DATA'
export const DOC_STATUS 	        = 'DOC_STATUS'

//ROLES 
export const ROLES_LIST 			= 'ROLES_LIST'
export const CREATE_ROLE  			= 'CREATE_ROLE'
export const EDIT_ROLE  			= 'EDIT_ROLE'
export const DELETE_ROLE  			= 'DELETE_ROLE'
export const FETCH_USER_SUCCESS		= 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE		= 'FETCH_USER_FAILURE'
export const CHANGE_PASSWORD		= 'CHANGE_PASSWORD'
export const PROFILE_SETTINGS		= 'PROFILE_SETTINGS'

// Email Setting
export const EDIT_EMAIL_SETTINGS = 'EDIT_EMAIL_SETTINGS'
export const CREATE_EMAIL_SETTINGS = 'CREATE_EMAIL_SETTINGS'

//MASTERS CONTACT US
export const MASTER_CONTACT_US_LIST		= 'MASTER_CONTACT_US_LIST'
export const MASTER_CONTACT_US_DATA		= 'MASTER_CONTACT_US_DATA'
export const MASTER_CREATE_CONTACT_US	= 'MASTER_CREATE_CONTACT_US'
export const MASTER_DELETE_CONTACT_US	= 'MASTER_DELETE_CONTACT_US'


//MASTERS FAQs
export const MASTER_FAQ_LIST			    = 'MASTER_FAQ_LIST'
export const MASTER_FAQ_DATA			    = 'MASTER_FAQ_DATA'
export const MASTER_CREATE_FAQ		        = 'MASTER_CREATE_FAQ'
export const MASTER_DELETE_FAQ		        = 'MASTER_DELETE_FAQ'


//MASTERS EQUIPMENTS
export const MASTER_EQUIPMENT_LIST			= 'MASTER_EQUIPMENT_LIST'
export const MASTER_EQUIPMENT_DATA			= 'MASTER_EQUIPMENT_DATA'
export const MASTER_CREATE_EQUIPMENT		= 'MASTER_CREATE_EQUIPMENT'
export const MASTER_DELETE_EQUIPMENT		= 'MASTER_DELETE_EQUIPMENT'

//MASTERS EQUIPMENTS
export const MASTER_FEES_LIST			= 'MASTER_FEES_LIST'
export const MASTER_FEES_DATA			= 'MASTER_FEES_DATA'
export const MASTER_FEES_CREATE		= 'MASTER_FEES_CREATE'

//MASTERS SERVICES
export const MASTER_SERVICE_LIST			= 'MASTER_SERVICE_LIST'
export const MASTER_SERVICE_DATA			= 'MASTER_SERVICE_DATA'
export const MASTER_CREATE_SERVICE		    = 'MASTER_CREATE_SERVICE'
export const MASTER_DELETE_SERVICE		    = 'MASTER_DELETE_SERVICE'

//MASTERS TYPES
export const MASTER_TYPE_LIST			    = 'MASTER_TYPE_LIST'
export const MASTER_TYPE_DATA			    = 'MASTER_TYPE_DATA'
export const MASTER_CREATE_TYPE		        = 'MASTER_CREATE_TYPE'
export const MASTER_DELETE_TYPE		        = 'MASTER_DELETE_TYPE'

//MASTERS AVAILABILITY
export const MASTER_AVAILABILITY_LIST	    = 'MASTER_AVAILABILITY_LIST'
export const MASTER_AVAILABILITY_DATA	    = 'MASTER_AVAILABILITY_DATA'
export const MASTER_CREATE_AVAILABILITY		= 'MASTER_CREATE_AVAILABILITY'
export const MASTER_DELETE_AVAILABILITY		= 'MASTER_DELETE_AVAILABILITY'

//MASTERS PATIENT
export const PATIENT_LIST			        = 'PATIENT_LIST'
export const CREATE_PATIENT			        = 'CREATE_PATIENT'
export const DELETE_PATIENT		            = 'DELETE_PATIENT'
export const GET_PATIENT_DATA		        = 'GET_PATIENT_DATA'
export const EDIT_PATIENT		        	= 'EDIT_PATIENT'
export const GET_FAVORITE_DOCTOR_LIST	= 'GET_FAVORITE_DOCTOR_LIST'
export const GET_FAVORITE_DOCTOR_DATA	= 'GET_FAVORITE_DOCTOR_DATA'

// Bank Details
export const GET_BANK_DETAILS		         = 'GET_BANK_DETAILS'
export const ADD_BANK_DETAILS		         = 'ADD_BANK_DETAILS'

export const MULTI_ACTION		            = 'MULTI_ACTION'
export const LOGIN		        		      = 'LOGIN'
export const LOGOUT		        		      = 'LOGOUT'
export const FORGOT_PASSWORD 			      = 'FORGOT_PASSWORD'
export const RESET_PASSWORD_EMAIL         = 'RESET_PASSWORD_EMAIL'
export const VALIDATE_OTP		       	   = 'VALIDATE_OTP'
export const RESEND_OTP		        	      = 'RESEND_OTP'
export const CHECK_IF_ALREADY_VERIFIED    = 'CHECK_IF_ALREADY_VERIFIED'


export const SAVE_TOKEN 	 			= 'SAVE_TOKEN'
export const UPDATE_ROLE_USER 			= 'UPDATE_ROLE_USER'
export const UPDATE_USER 				=  'UPDATE_USER'
export const EDIT_USER 					=  'EDIT_USER'
export const DOCTOR_STATUS 				=  'DOCTOR_STATUS'

//Booking
export const DOCTOR_SEARCH_LIST 		=  'DOCTOR_SEARCH_LIST'
export const SUGGEST_DOCTORS 			=  'SUGGEST_DOCTORS'
export const REQUEST_APPOINTMENT_LIST 	=  'REQUEST_APPOINTMENT_LIST'
export const GET_DOCTOR_SUGGEST 		=  'GET_DOCTOR_SUGGEST'
export const SUGGEST_TO_PATIENT 		=  'SUGGEST_TO_PATIENT'
export const GET_PATIENT_DETAILS 		=  'GET_PATIENT_DETAILS'
export const PATIENT_APPOINTMENT		=  'PATIENT_APPOINTMENT'
export const DOCTOR_APPOINTMENT			=  'DOCTOR_APPOINTMENT'
export const APPOINTMENT_STATUS			=  'APPOINTMENT_STATUS'
export const GET_DOCTORS_DETAILS		=  'GET_DOCTORS_DETAILS'
export const GET_BOOKING_DETAILS 		=  'GET_BOOKING_DETAILS'
export const CREATE_APPOINTMENT 		=  'CREATE_APPOINTMENT'
export const DASHBOARD_LIST 			=  'DASHBOARD_LIST'
export const GET_PATIENT_APPOINTMENT_DATA =  'GET_PATIENT_APPOINTMENT_DATA'
export const ATTACH_RECORD 				=  'ATTACH_RECORD'
export const PRESCRIPTION_ADD 			=  'PRESCRIPTION_ADD'
export const GET_EQUIPMENT_LIST 			=  'GET_EQUIPMENT_LIST'
export const GET_PRESCRIPTION_DATA 		=  'GET_PRESCRIPTION_DATA'
export const GET_PATIENT_DOCTOR_DATA 		=  'GET_PATIENT_DOCTOR_DATA'
export const GET_PATIENT_LIST 			=  'GET_PATIENT_LIST'
export const BOOKING_REQUEST 			=  'BOOKING_REQUEST'
export const MASTER_TYPE_ALL_LIST 		=  'MASTER_TYPE_ALL_LIST'
export const MASTER_SERVICE_ALL_LIST 	=  'MASTER_SERVICE_ALL_LIST'
export const MASTER_AVAILABILITY_ALL_LIST 	=  'MASTER_AVAILABILITY_ALL_LIST'
export const DATE_TIME_ARRAY      			=  'DATE_TIME_ARRAY'

export const DOCTOR_BOOK_SLOTS      		=  'DOCTOR_BOOK_SLOTS'

// Payout
export const DOCTOR_PAYOUT			=  'DOCTOR_PAYOUT'


//
export const ORDERS_BOOKING      		=  'ORDERS_BOOKING'
export const MASTER_ABOUT_US_DATA      	=  'MASTER_ABOUT_US_DATA'
export const MASTER_CREATE_ABOUT_US     =  'MASTER_CREATE_ABOUT_US'
export const HOMEPAGE_DATA     =  'HOMEPAGE_DATA'
export const MASTER_CREATE_BLOG     =  'MASTER_CREATE_BLOG'
export const MASTER_BLOG_DATA     =  'MASTER_BLOG_DATA'
export const MASTER_BLOG_LIST     =  'MASTER_BLOG_LIST'
export const VIEW_ARTICEL     =  'VIEW_ARTICEL'
export const GET_CONDTION     =  'GET_CONDTION'

export const MASTER_ASSOCIATE_PARTNERS_DATA     =  'MASTER_ASSOCIATE_PARTNERS_DATA'
export const MASTER_ASSOCIATE_PARTNERS_LIST     =  'MASTER_ASSOCIATE_PARTNERS_LIST'
export const MASTER_CREATE_ASSOCIATE_PARTNERS     =  'MASTER_CREATE_ASSOCIATE_PARTNERS'
export const MASTER_CREATE_TESTIMONIALS     =  'MASTER_CREATE_TESTIMONIALS'
export const MASTER_TESTIMONIALS_LIST     =  'MASTER_TESTIMONIALS_LIST'
export const MASTER_TESTIMONIALS_DATA     =  'MASTER_TESTIMONIALS_DATA'
export const CREATE_CONTACTUS  =  'CREATE_CONTACTUS'
export const CAREERS_LIST  =  'CAREERS_LIST'
export const EDIT_CAREERS  =  'EDIT_CAREERS'


//Payment
export const PAYMENT_ORDER  =  'PAYMENT_ORDER'
export const GET_MEDICALHISTORY  =  'GET_MEDICALHISTORY'
export const SUBMIT_CONSULTATON_FORM  =  'SUBMIT_CONSULTATON_FORM'
export const GET_CONSULTATION  =  'GET_CONSULTATION'







